version: '3'
services:
  # my-node-app:
  #   image: 613363943992.dkr.ecr.sa-east-1.amazonaws.com/my-node-app:1.0
  #   # image: my-node-app:1.0
  #   ports:
  #     - 3000:3000
  my-mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:    
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # to know this we need to know where mongodb saves its data
      # search where it is, and take a look inside the container
      - mongo-data:/data/db
      # here it is without space
  my-mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:    
      - ME_CONFIG_MONGODB_SERVER=my-mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password

volumes:
  mongo-data:
    # this is an aditional information for docker
    driver: local
