# Generated by Django 4.1.3 on 2022-12-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="profile_pic",
            new_name="profile_image",
        ),
    ]
