FROM node:16-alpine

WORKDIR "/app"

COPY package.json .
RUN npm install
# to solve a problem with 
# [eslint] EACCES: permission denied, mkdir '/app/node_modules/.cache'
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD ["npm", "run", "start"]